stages:
  - lint
  - format
  - deploy

cache:
  key:
    files: 
      - package-lock.json  
  paths:
    - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline

eslint:
  image: node:20.13.1-alpine
  stage: lint
  script:
    - npm install
    - npm run lint

prettier:
  image: node:20.13.1-alpine
  stage: format
  script:
    - npm install
    - npm run format

deploy:
  image: node:20.13.1-alpine
  stage: deploy
  script: 
    - eval $(ssh-agent -s)
    - echo $SSH_PRIVATE_KEY" | tr -d '\r' ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - scp . deploy@142.93.177.172:~/realworld
